const colleges = [
  `A C T College of Engineering and Technology, Nelvoy Village, Pukkathurai Post, Maduranthagam, Chengalpattu District 603107`,
  `A K T Memorial College of Engineering and Technology, Neelamangalam Village, Kallakurichi District 606202`,
  `A R College of Engineering and Technology, Kadayam-Alangulam Road, Therikkumadathoor Post, Tenkasi District 627423`,
  `A R Engineering College, Vadakuchipalayam, Kappiyampuliyur Post, Villupuram District 605601`,
  `A R J College of Engineering and Technology, Mannargudi Taluk, Thiruvarur District 614001`,
  `A V C College of Engineering, Mannampandal Post, Mayiladuthurai, Nagappattinam District 609305`,
  `A V S Engineering College, Military Road, Ammapet, Salem District 636003`,
  `AAA College of Engineering and Technology, Kamarajar Educational Road, Amathur Village, Sivakasi, Virudhunagar District 626005`,
  `Aalim Muhammed Salegh College of Engineering, Muthapudupet, Avadi IAF, Chennai 600055`,
  `Adhi College of Engineering and Technology, Pazhayaseevaram, Madura Sankarapuram Village, Kancheepuram District 631605`,
  `Adhiparasakthi College of Engineering, Kalavai, Ranipet District 632506`,
  `Adhiparasakthi Engineering College, Melmaruvathur, Chengalpattu District 603319`,
  `Adhiyamaan College of Engineering (Autonomous), Hosur, Krishnagiri District 635109`,
  `Adithya Institute of Technology, Kurumbapalayam Village, Coimbatore District 641107`,
  `Agni College of Technology, Old Mahabalipuram Road (OMR), Thalambur Village, Chengalpattu District 603103`,
  `Aishwarya College of Engineering and Technology, Errattaikaradu Paruvachi Post, Anthiyur (Via), Bhavani Taluk, Erode District 638312`,
  `Akshaya College of Engineering and Technology, Kinathukadavu, Coimbatore District 642109`,
  `Alagappa Chettair Government College of Engineering and Technology (Autonomous), Karaikudi, Sivagangai District 630004`,
  `Al-Ameen Engineering College (Autonomous), Karundevan Palayam, Nanjai Uthukuli Post, Erode District 638104`,
  `Alpha College of Engineering, Dr. Grace George Nagar, Udayavar Koil Street, Thirumazhisai, Poonamalle, Chennai 602107`,
  `Ambal Professional Group of Institutions, Coimbatore to Trichy Road, K N Puram Post, Palladam Taluk, Tiruppur District 641662`,
  `AMRITA College of Engineering and Technology, Erachakulam Post, Kanyakumari District 629902`,
  `Anand Institute of Higher Technology, Old Mahabalipuram Road (OMR), Kazhipattur, Chengalpattu District 603103`,
  `Angel College of Engineering and Technology, P.K.Palayam, Ugayanur Village, Tirupur District 641 665`,
  `Anjalai Ammal-Mahalingam Engineering College, Kovilvenni, Thiruvarur District 614403`,
  `Anna University Regional Campus - Coimbatore, Maruthamalai Main Road, Navavoor Bharathiyar University Post, Somayampalayam,
 Coimbatore District 641046`,
  `Anna University Regional Campus - Madurai, Kanyakumari National Highway, Keelakuilkudi, Madurai District 625019`,
  `Anna University Regional Campus - Tirunelveli, Trivandrum Road, Palayamkottai, Tirunelveli District 627007`,
  `Annai College of Engineering and Technology, Kovilacheri, Kumbakonam, Thanjavur District 612503`,
  `Annai Mathammal Sheela Enginereing College, Erumapatty Post, Namakkal District 637013`,
  `Annai Mira College of Engineering and Technology, Arcot Road, Arappakkam Village, Walaja Taulk, Ranipet District 632 517`,
  `Annai Terasa College of Engineering, Thirunavalur, Kallakkurichi District 607204`,
  `Annai Vailankanni College of Engineering, Pothaiyadi Salai, Pottalkulam, Azhagappapuram, Kanyakumari District 629401`,
  `Annai Veilankannis College of Engineering, Gandhi Road, Nedungundram, Chennai 600048`,
  `Annamalai University Faculty of Engineering and Technology,Annamalai nagar,Cuddalore`,
  `Annamalaiar College of Engineering, Modaiyur Village, Polur Taluk, Thiruvannamalai District 606902`,
  `Annaporna Engineering College, Sankari Main Road, NH-47, Periaseeragapadi, Salem District 636308`,
  `Apollo Engineering College, Mevaloorkuppam, Valarpuram Post, Sriperumpudur, Kancheepuram District 602105`,
  `Arasu Engineering College, Chennai Main Road, Kumbakonam, Thanjavur District 612501`,
  `Arifa Institute of Technology(Formly Haji sheik Ismail Engineering College), Esanoor, Keelaiyur Post, Thirukkuvalai Taluk, Nagapattinam
 District 611103`,
  `Arignar Anna Institute of Science and Technology, Pennalur, Sriperumpudur Taluk, Kancheepuram District 602105`,
  `Ariyalur Engineering College, NH-227, Trichy-Chithambaram NH, Karuppur-Senapathy Post, Ariyalur District 621707`,
  `Arjun College of Technology, Chettiyakkapalayam, Kinathukadavu, Coimbatore District 642120`,
  `Arulmigu Meenakshi Amman College of Engineering, Vadamavandal,Thiruvannamalai District 604410`,
  `Arulmurugan College of Engineering, Karvazhi Road, Thennilai Post, Karur District 639206`,
  `Arunachala College of Engineering for Women, Thanka Gardens, Manavilai, Vellichanthai, Nagercoil, Kanyakumari District 629203`,
  `Arunai Engineering College, Mathur, Thiruvannamalai District 606603`,
  `Asan Memorial College of Engineering and Technology,Chengalpattu- 603 001.`,
  `Asian College of Engineering and Technology, Asian College Road, Kondayampalayam, Near Saravanampatti, Coimbatore District
 641110`,
  `As-Salam College of Engineering and Technology, Thirumangalakudi, Aduthurai, Thiruvidaimaruthur, Thanjavur District 612102`,
  `AVS College of Technology, Attur Main Road, Near AVS College of Arts & Science, Chinnagoundapuram, Salem District 636106`,
  `Bannari Amman Institute of Technology (Autonomous), Sathyamanagalam, Erode District 638401`,
  `Bethlahem Institute of Engineering, Karungal, Kanyakumari District 629157`,
  `BHAJARANG ENGINEERING COLLEGE,AYATHUR VILLAGE, VEPPAMPATTU(R.S),THIRUVALLUR`,
  `Bharath Niketan Engineering College, Thimmarasanaickanoor, Aundipatti, Theni District 625536`,
  `Bharathidasan Engineering College, Nattrampalli Post, Thiruppathur District 635854`,
  `Bharathiyar Institute of Engineering for Women, Deviayakurichi, Attur Taluk, Salem District 636112`,
  `Builders engineering college, Nathakadaiyur, Erode Road, Palayakottai Village, Kangeyam, Tiruppur District 638108`,
  `C Abdul Hakeem College of Engineering and Technology, Melvisharam, Ranipet District 632509`,
  `C K College of Engineering and Technology, Chellangkuppam, Cuddalore District 607003`,
  `C M S College of Engineering and Technology, Appachigoundenpathy, Kumittipatti, Coimbatore District 641105`,
  `C M S College of Engineering, Emapuram Post, Namakkal District 637003`,
  `C S I College of Engineering, Ketti, The Nilgiris 643215`,
  `C S I Institute of Technology, Thovalai, Kanyakumari District 629302`,
  `C.A.R.E Group of Institutions, Thayanoor Village, Thayanoor Village, Kuttappatti, Srirangam Taluk, Tiruchirappalli District 620009`,
  `CAPE Institute of Technology, Levingipuram, Tirunelveli District 627114`,
  `Central Electrochemical Research Institute CECRI), Karaikudi, Sivagangai District 630006`,
  `Central Institute of Plastics Engineering and Technology (CIPET), Guindy, Chennai 600032`,
  `Chendu College of Engineering & Technology, Zamin Endathur Village, Madurantakam Taluk, Chengalpattu District 603331`,
  `CHENDURAN COLLEGE OF ENGINEERING THIRUMAYAM PUDUKOTTAI
 - 622507`,
  `Chennai Institute of Technology, Puduper Village, Nandambakkam Post, Kundrathur, Chennai 600069`,
  `Cheran College of Engineering, Karur-Coimbatore Main Road, NH-67, K.Paramathi Post, Aravakurichi Taluk, Karur District 639111`,
  `Chettinad College of Engineering and Technology, NH-67, Trichy Main Road, Puliyur C F, Karur District 639114`,
  `Christ the King Engineering College, Cecilia Gardens, Chikkarampalayam Village, Coimbatore District 641104`,
  `Christian College of Engineering and Technology, Oddanchatram, Dindigul District 624619`,
  `Coimbatore Institute of Engineering and Technolgoy (Autonomous), Narasipuram Post, Coimbatore District 641109`,
  `Coimbatore Institute of Technology (Autonomous), Civil Aerodrome Post, Coimbatore District 641014`,
  `D M I College of Engineering, Palanchoor, Nazrethpet, Chennai 602103`,
  `D M I Engineering College, Aralvaimozhi Village, Thovalai, Kanyakumari District 629301`,
  `Dhaanish Ahmed College of Engineering, Padappai, Chennai 601301`,
  `Dhaanish Ahmed Institute of Technology, Pichanur Post, (Near K G Chavadi), Coimbatore District 641105`,
  `Dhanalakshmi College of Engineering, Manimangalam, Chennai 601301`,
  `Dhanalakshmi Srinivasan Engineering College (Autonomous), Thuraiyur Road, Perambalur District 621212`,
  `Dhanalakshmi Srinivasan College of Engineering and Technology, East Coast Road, Poonjeri, Chennai 603104`,
  `Dhanalakshmi Srinivasan College of Engineering, NH47, Palakkad Main Road, Navakkarai Post, Near Nandhi Temple, Coimbatore
 District 641105`,
  `Dhanalakshmi Srinivasan Institute of Research and Technology, NH- 45, Trichy?Chennai Main Road, Siruvachur, Perambalur District
 621113`,
  `Dhanalakshmi Srinivasan Institute of Technology, Samayapuram, Chennai-Trichy Main Road, Tiruchirappalli District 621112`,
  `Dhirajlal Gandhi College of Technology, Sikkanampatty, (Opp. to Airport), Omalur Taluk, Salem District 636309`,
  `Dr. G U Pope College of Engineering, Sawyerpuram, Thoothukudi District 628251`,
  `Dr. Mahalingam College of Engineering and Technology (Autonomous), Mackinaickenpatti Post, Pollachi Taluk, Coimbatore
 District 642003`,
  `Dr. N G P Institute of Technology, Kalapatti Road, Coimbatore District 641035`,
  `Dr. Nagarathinams College of Engineering, Anadhagoundam Palayam, Minakkal Post, Rasipuram, Namakkal District 637505`,
  `Dr. Navalar Nedunchezhian College of Engineering, Tholudur, Cuddalore District 606303`,
  `Dr. Sivanthi Aditanar College of Engineering, Tiruchendur, Thoothukudi District 628215`,
  `E G S Pillay Engineering College (Autonomous), Nagapattinam District 611002`,
  `EASA College of Engineering and Technology, NH-47, Coimbatore- Palakkad Main Road, Navakarai Post, Coimbatore District 641105`,
  `Easwari Engineering College (Autonomous), Ramapuram, Chennai 600089`,
  `Einstein College of Engineering, Seethaparpanallur, Tirunelveli District 627012`,
  `Er. Perumal Manimekalai College of Engineering, Near Koneripalli, Hosur, Krishnagiri District 635117`,
  `Erode Sengunthar Engineering College (Autonomous), Thudupathi Post, Erode District 638057`,
  `Excel College of Engineering and Technology, Pallakapalayam, Sankari West Post, Namakkal District 637303`,
  `Excel Engineering College (Autonomous), Pallakkapalayam, Sankari West Post, Namakkal District 637303`,
  `Fatima Michael College of Engineering & Technology, Sengottai Village, Sivagangai Main Road, Madurai District 625020`,
  `Francis Xavier Engineering College (Autonomous), Vannarpettai, Tirunelveli District 627003`,
  `G K M College of Engineering and Technology, Alappakkam-Mappedu Road, Chennai 600063`,
  `Ganadipathy Tulsi�s Jain Engineering College, Kaniyambadi, Vellore
 District 632102`,
  `Ganapathy Chettiar College of Engineering and Technology, Melakavanur Post, Paramakudi, Ramanathapuram District 623706`,
  `Ganesh College of Engineering, Attur Main Road, Mettupatti, Salem District 636111`,
  `Global Institute of Engineering and Technology, Bangalore-Chennai Highway, Melvisharam, Walajah Taluk, Ranipet District 632506`,
  `Gnanamani College of Technology, Pachal Post, Namakkal District 637018`,
  `Gojan School of Business and Technology, Alamathi, Chennai 600062`,
  `GOOD SHEPHERD COLLEGE OF ENGINEERING AND TECHNOLOGY, MARUTHAMPARAI, KANYAKUMARI`,
  `Government College of Engineering (Autonomous), Bargur, Krishnagiri District 635104`,
  `Government College of Engineering (Autonomous), Karuppur, Salem District 636011`,
  `Government College of Engineering, Chettikkarai Post, Dharmapuri District 635704`,
  `Government College of Engineering, Gandarvakottai Road, Sengipatti, Thanjavur District 613402`,
  `Government College of Engineering, Melachokkanathapuram, Bodinayakkanur, Theni District 625582`,
  `Government College of Engineering, Srirangam, Sethurappatti, Tiruchirappalli District 620012`,
  `Government College of Engineering, Tirunelveli District 627007`,
  `Government College of Technology (Autonomous), Thadagam Road, Coimbatore District 641013`,
  `Grace College of Engineering, Chandy Nagar, Mullakkadu, Thoothukudi District 628005`,
  `GRT Institute of Engineering and Technology, GRT Mahalakshmi Nagar, Chennai-Tirupathi Highway, Tiruttani Taluk, Thiruvallur District
 631209`,
  `Hindustan Institute of Technology (Autonomous), Othakkalmandapam, Coimbatore District 641032`,
  `Hindusthan College of Engineering and Technology (Autonomous), Othakkalmandapam Post, Coimbatore District 641032`,
  `Holy Cross Engineering College, Vagaikulam, Sri Mulakarai, Srivaikuntam, Thoothukudi District 628851`,
  `HOSUR INSTITUTE OF TECH AND SCIENCE, Errandapalli Village, Hosur Taluk, Krishnagiri District`,
  `I F E T College of Engineering (Autonomous), Gangarampalayam, Villupuram District 605108`,
  `Idhaya Engineering College for Women, Chinnasalem, Kallakkurichi District 606201`,
  `Imayam College of Engineering, Kannanur, Thuraiyur, Tiruchirappalli District 621206`,
  `Immanuel Arasar J J College of Engineering, Anappara, Edavilagam, Nattalam, Kanyakumari District 629195`,
  `Indian Institute of Handloom Technology, Foulke's Compound, Thillai Nagar, Salem District 636001`,
  `Indira Institute of Engineering and Technology, VGR Gardens, Pandur, Thiruvallur District 631203`,
  `Indra Ganesan College of Engineering, Madurai Main Road, Manikandam, Tiruchirappalli District 620012`,
  `Infant Jesus College of Engineering, Thoothukudi Highway (NH7/A), Thoothukudi District 628851`,
  `INFO Institute of Engineering, Sarkar Samakulam, Coimbatore District 641107`,
  `Institute of Road and Transport Technology, Vasavi College Post, Erode District 638316`,
  `J C T College of Engineering and Technology, Pichanur, Coimbatore District 641105`,
  `J J College of Engineering and Technology, Poolankulathupatti Post, Thiruchirappalli District 620009`,
  `J K K Muniraja College of Technology, T N Palayam, Gobi Taluk, Erode District 638506`,
  `J K K Nataraja College of Engineering and Technology, Komarapalayam Amani, Thattankuttai Panchayat, Namakkal District
 638183`,
  `J N N Institute of Engineering, Ushaa Garden, Kannigaipair Village, Uthukottai Taluk, Thiruvallur District 601102`,
  `J P College of Engineering, College Road, Ayakudy, Tenkasi Taluk, Tenkasi District 627852`,
  `Jagannath Institute of Technology, Thandalam Village, Thiruporur, Kancheepuram District 603110`,
  `Jai Shriram Engineering College, Dharapuram Road, Avinashi Palayam, Tiruppur District 638660`,
  `Jainee College of Engineering and Technology, Dindigul-Theni Main Road (Near Vakkampatti), Dindigul District 624303`,
  `Jairupaa College of Engineering, Thottiapalayam, Kathankanni Post, Kangayam, Tiruppur District 641 604`,
  `Jansons Institute of Technology, Karumathampatty, Somaur, Coimbatore District 641659`,
  `Jawahar Engineering College, Kaveri Rangan Nagar, Saligramam, Chennai 600093`,
  `Jaya College of Engineering and Technology, Parivakkam, Poonamallee, Chennai 600056`,
  `Jaya Engineering College, Thirunindravur, Chennai 602024`,
  `Jaya Institute of Technology, Kanchipadi Post, Thiruvallur-Tiruttani NH Road, Thiruvallur District 631204`,
  `Jaya Sakthi Engineering College, Thirunindravur, Chennai 602024`,
  `Jayalakshmi Institute of Technology, Thoppur, Dharmapuri District 635352`,
  `Jayam College of Engineering and Technology, Nallanur Post, Dharmapuri District 636813`,
  `Jayamatha Engineering College, Aralvaimozhi, Kanyakumari District - 629301`,
  `Jayaraj Annapackiam CSI College of Engineering, Nazareth, Thoothukudi District 628617`,
  `Jayaram College of Engineering and Technology , Pagalavadi Post, Tiruchirappalli District 621014`,
  `Jeppiaar Institute of Technology,kunnam Village,Sriperumpudur Taulk,Kancheepuram District 631604`,
  `Jeppiaar SRR Engineering College, Old Mahabalipuram Road, Chengalpattu District 603103`,
  `Jeppiar Engineering College, Old Mahabalipuram Road (OMR), Chennai 600119`,
  `Jerusalem College of Engineering (Autonomous), Narayanapuram, Pallikaranai, Chennai 600 100`,
  `K C G College of Technology, Karappakkam, Chennai 600096`,
  `K L N College of Engineering (Autonomous), Pottapalayam, Sivagangai District 630611`,
  `K P R Institute of Engineering and Technology (Autonomous), Kollupalayam Village, Arasur Panchayat, Coimbatore District 641407`,
  `K Ramakrishnan College of Engineering (Autonomous),
 Kariyamanickam Road, Samayapuram, Manachanallur Taluk, Tiruchirappalli District 621112`,
  `K Ramakrishnan College of Technology, Kariyamanickam Road, Samayapuram, Manachanallur Taluk, Tiruchirappalli District 621112`,
  `K S K College of Engineering and Technology, Thanjavur Main Road, Darasuram, Kumbakonam, Thanjavur District 612702`,
  `K S R College of Engineering (Autonomous), Tiruchengode, Namakkal District 637215`,
  `K S R Institute for Engineering and Technology, Thokkavadi, Namakkal District 637215`,
  `K S Rangasamy College of Technology (Autonomous), Tiruchengode, Namakkal District 637215`,
  `Kalaignar Karunanidhi Institute of Technology (Autonomous), Kannampalayam, Coimbatore District 641402`,
  `Kamaraj College of Engineering and Technology (Autonomous), Virudhunagar District 626001`,
  `KANCHI PALLVAN ENGINEERING COLLEGE`,
  `Karaikudi Institute of Technology, KIT & KIM Technical Campus, Keeranipatti, Thalakkuvur, Karaikudi, Sivagangai District 630307`,
  `Karpagam College of Engineering (Autonomous), Othakkalmandapam, Coimbatore District 641032`,
  `Karpagam Institute of Technology, Seerapalayam Village, L&T By pass Road, Coimbatore District 641021`,
  `Karpagavinayaga College of Engineering and Technology, Palayanoor Post, Maduranthagam Taluk, Chengalpattu District 603308`,
  `Kathir College of Engineering, Neelambur, Avinashi Road, Coimbatore District 641062`,
  `KGISL Institute of Technology, KGISL Campus, Thudiyalur Road, Saravanampatti, Coimbatore District 641035`,
  `King College of Technology, Nallur, N Pudupatty Post, Namakkal District 637020`,
  `Kings College of Engineering, Punalkulam, Pudukkottai District 613303`,
  `Kings Engineering College, Sriperumpudur Taluk, Kancheepuram District 602105`,
  `Kingston Engineering College, Chithoor Main Road, Christianpet Village, Katpadi Taluk, Vellore District 632059`,
  `Knowledge Institute of Technology, KIOT Campus, Kakapalayam Post, Salem District 637504`,
  `Kongu Engineering College (Autonomous), Perundurai, Erode District 638052`,
  `Kongunadu College of Engineering and Technology (Autonomous), Tholurpatti, Thottiyam, Tiruchirappalli District 621215`,
  `Krishnaswamy Collge of Engineering and Technology, S Kumarapuram, Cuddalore District 607109`,
  `Kumaraguru College of Technology (Autonomous), Chinnavedampatti Post, Coimbatore District 641006`,
  `Kurinji College of Engineering and Technology, Manapparai, Tiruchirappalli District 621307`,
  `Latha Mathavan Engineering College, Kidaripatti Post, Alagarkoil (Via), Melur Taluk, Madurai District 625301`,
  `Lord Jegannath College of Engineering and Technology, Kumarapuram, Thoppur Post, Kanyakumari District 629402`,
  `Lord Venkateshwara Engineering College, Walajabad Post, Kancheepuram District 631605`,
  `Lourdes Mount College of Engineering and Technology, Marthandam- Karungal Road, Chundavilai, Mullanganavilai, Nattalam Post,
 Kanyakumari District 629195`,
  `Loyola Institute of Technology and Science, Loyola Nagar, P B No.2, Thovalai, Kanyakumari District 629302`,
  `Loyola Institute of Technology, Mevaloorkuppam, B Village, Palanchoor, Nazarethpet Post, Chennai 600123`,
  `Loyola-ICAM College of Engineering and Technology, Loyola College Campus, Nungambakkam, Chennai 600034`,
  `M E T Engineering College, Mogals Garden, Thovalai Village, Aralvaimozhi Town Panchayat, Thovalai, Kanyakumari District 629304`,
  `M I E T Engineering College, Trichy-Pudukkottai Road, Tiruchirappalli District 620007`,
  `M Kumarasamy College of Engineering (Autonomous), Thalavapalayam, Karur District 639113`,
  `M N S K College of Engineering, Vallathirakkottai Post, Pudukkottai District 622305`,
  `M P Nachimuthu M Jagannathan Engineering College, Chennimalai, Erode District 638112`,
  `M R K Institute of Technology, Nattarmangalam Village, Kattumannarkoil, Cuddalore District 608306`,
  `M.A.M. College of Engineering and Technology, Trichy-Chennai Trunk Road, Siruganur, Tiruchirappalli District 621105`,
  `M.A.M. College of Engineering, Siruganur, Tiruchirappalli District 621105`,
  `M.A.M. School of Engineering, Siruganur, Tiruchirappalli District 621105`,
  `Madha Engineering College, Kundrathur, Chennai 600069`,
  `Madha Institute of Engineering and Technology, Erandamkattalai Village, Sadhananthapuram, Thandalam Post, Chennai 602101`,
  `Madurai Institute of Engineering & Technology, Pottapalayam Village, Manamadurai Taluk, Sivagangai District 630611`,
  `Maha Bharathi Engineering College, A Vasudevanur, Chinnasalem, Kallakurichi District 606201`,
  `Mahakavi Bharathiyar College of Engineering and Technology, Vasudevanallur, Tenkasi District 627758`,
  `Mahalakshmi Engineering College, Trichy-Salem Highways, (Near
 No.1 Tollgate), Melpathu, Siruganbur Post, Tiruchirappalli District 621213`,
  `Mahath Amma Institute of Engineering and Technology (MIET), Ariyur, Annavasal Road, Illupur Taluk, Pudukkottai District 622101`,
  `Mahendra College of Engineering, Attur Road, Minnampalli, Valapady, Salem District 636106`,
  `Mahendra Engineering College (Autonomous), Mahendhirapuri, Mallasamudram, Namakkal District 637503`,
  `Mahendra Engineering College for Women, Kumaramangalam, Namakkal District 637205`,
  `Mahendra Institute of Engineering and Technology, Mahendrapuri, Mallasamudram, Namakkal District 637503`,
  `Mahendra Institute of Technology (Autonomous), Mahendhirapuri, Mallasamudram, Namakkal District 637503`,
  `Mailam Engineering College, Mailam, Villupuram District 604304`,
  `Mangayarkarasi College of Engineering, First Street, Mangayarkarasi Nagar, Paravai, Madurai District 625402`,
  `MAR Ephraem College of Engineering & Technology, Malankara Hills, Elavuvillai, Marthandam, Kanyakumari District 629171`,
  `Maria College of Engineering and Technology, Attoor Puliyamoodu Junction, Thiruvattar Post, Kanyakumari District 629177`,
  `Marthandam College of Engineering & Technology, Kuttakuzhi, Veeyanoor Post, Kanyakumari District 629177`,
  `Meenakshi College of Engineering, Vembuliamman Koil Street, K K Nagar (West), Chennai 600078`,
  `Meenakshi Ramaswamy Engineering College, Trichy Main Road, Thathanur, Udayarpalayam, Ariyalur District 621804`,
  `Meenakshi Sundararajan Engineering College, Kodambakkam, Chennai 600024`,
  `Mepco Schlenk Engineering College (Autonomous), Sivakasi, Virudhunagar District 626005`,
  `Misrimal Navajee Munoth Jain Engineering College, Rajiv Gandhi Salai (OMR), Thorappakkam, Chennai 600096`,
  `Mohamed Sathak A J College of Engineering, Old Mahabalipuram Road (OMR), Egattur, Chengalpattu District 603103`,
  `Mohamed Sathak Engineering College, Kilakarai, Ramanathapuram District 623806`,
  `Mookambigai College of Engineering, Keeranur, Pudukkottai District 622502`,
  `Mother Terasa College of Engineering and Technology, Mettusalai Post and Taluk, Pudukkottai District 622102`,
  `Mount Zion College of Engineering and Technology, Pilivalam Post, Pudukkottai District 622507`,
  `Muthayammal College of Engineering, Kakkaveri Post, Namakkal District 637408`,
  `Muthayammal Engineering College (Autonomous), Rasipuram, Namakkal District 637408`,
  `N P R College of Engineering and Technology, Natham, Dindigul District 624003`,
  `N S N College of Engineering and Technology, Karur-Madurai NH7, Manalmedu, Karur District 639003`,
  `Nadar Saraswathi College of Engineering and Technology, Vadupudupatti, Annanji Post, Theni District 625531`,
  `Nandha College of Technology, Pitchandampalayam Post, Erode District 638052`,
  `Nandha Engineering College (Autonomous), Pitchandampalayam Post, Erode District 638052`,
  `Narasus Sarathy Institute of Technology, Poosaripatty Village, Omalur Taluk, Salem District 636305`,
  `Narayanaguru College of Engineering, Manjalumoodu, Kanyakumari District 629151`,
  `National Engineering College (Autonomous), Kovilpatti, Thoothukudi District 628503`,
  `Nehru Institute of Engineering and Technology, Thirumalayampalayam Post, Coimbatore District 641105`,
  `Nehru Institute of Technology, Thirumalayampalayam Post, Coimbatore District 641105`,
  `Nellai College of Engineering, Maruthakulam Post, Tirunelveli District 627151`,
  `Nelliandavar Institute of Technology, Nerunjikorai Village, Pudhupalayam, Ariyalur Taluk, Ariyalur District 621704`,
  `New Prince Shri Bhavani College of Engineering and Technology, Vengaivasal Main Road, Gowriwakkam, Chennai 600073`,
  `OASYS Institute of Technology , Pulivalam Village, Musiri Taluk, Tiruchirappalli District 626001`,
  `Oxford College of Engineering, Venmani Village, Karaipoondi Post, Polur Taluk, Thiruvannamalai District 606803`,
  `Oxford Engineering College, Pirattiyur(W), Tiruchirappalli District 620009`,
  `P A College of Engineering and Technology (Autonomous), Palladam Road, Pollachi, Coimbatore District 642002`,
  `P B College of Engineering, Irungkattukottai, Sriperumpudur Taluk, Kancheepuram District 602105`,
  `P G P College of Engineering and Technology, Paramathi Post, Namakkal District 637207`,
  `P M R Engineering College, Adayalampattu, Maduravoyal , Vanagaram, Chennai 600095`,
  `P P G Institute of Technology, Vilankurichi Village, Coimbatore District 641035`,
  `P R Engineering College, Vallam, Thanjavur District 613403`,
  `P S N A Colllege of Engineering and Technology, Dindigul District 624622`,
  `P S N College of Engineering and Technology (Autonomous), Melathediyoor, Tirunelveli Dstrict 627152`,
  `P S N Engineering College, Melathediyoor, Tirunelveli District 627152`,
  `P S N Institute of Technology & Science, Melathediyoor, Tirunelveli District 627152`,
  `P S R Engineering College (Autonomous), Appayanaickenpatti, Sevalpatti, Virudhunagar District 626140`,
  `P S R Rengasamy College of Engineering for Women, Appayanaickenpatti, Sevalpatti, Virudhunagar District 626140`,
  `P S V College of Engineeering and Technology, Mittapalli, Balinayanapalli Post, Elathagiri, Krishnagiri District 635108`,
  `P T Lee Chengalvaraya Naicker College of Engineering and Technology, Oovery, Veliyur Post, Kancheepuram District 631 502`,
  `P T R College of Engineering and Technology, Austinpatty Post, Madurai District 625008`,
  `Paavai College of Engineering, NH-7, Pachal Post, Namakkal District 637018`,
  `Paavai College of Technology, NH-7, Pachal Post, Namakkal District 637018`,
  `Paavai Engineering College (Autonomous) , NH-7, Pachal Post, Namakkal District 637018`,
  `Pallavan College of Engineering, Thimmasamudram, Kancheepuram District 631502`,
  `Pandian Saraswathi Yadav Engineering College, Thirumansolai Post, Sivagangai District 630 561`,
  `Panimalar Engineering College, Nazarethpet, Poonamallee, Chennai 602103`,
  `Panimalar Institute of Technology, Nazarethpet, Poonamallee, Chennai 602103`,
  `Parisutham Institute of Technology and Science, Ring Road, Nanjikottai, Thanjavur District 613006`,
  `Park College of Engineering and Technology, Kaniyur, Coimbatore District 641659`,
  `Pavendhar Bharathidasan College of Engineering and Technology, Pudukkottai Main Road, Tiruchirappalli District 620024`,
  `PERI Institute of Technology, Mannivakkam, West Tambaram, Chennai 600048`,
  `PET Engineering College, Vallioor Post, Tirunelveli District 627117`,
  `Podhigai College of Engineering and Technology, Vinayakapuram, Adiyur Post, Tirupattur District 635601`,
  `Pollachi Institute of Engineering and Technology, Main Road, Poosaripatti, Pollachi Taluk, Coimbatore District 642205`,
  `Ponjesly College of Engineering, Vettornimadam Post, Nagercoil, Kanyakumari District 629003`,
  `Prathyusha Engineering college, Aranvoyalkuppam, Thiruvallur District 602025`,
  `Prince Dr. K Vasudevan College of Engineering and Technology, Medavakkam-Mambakkam Road, Ponmar, Chennai 600048`,
  `Prince Shri Venkateshwara Padmavathy Enginering College, Ponmar, Chennai 600048`,
  `Priyadarshini Engineering College, Vaniyambadi Post, Thiruppattur District 635751`,
  `PSG College of Technology (Autonomous), Peelamedu, Coimbatore District 641004`,
  `PSG Institute of Advanced Studies, Peelamedu, Coimbatore District 641004`,
  `PSG Institute of Technology and Applied Research, Avinashi Road, Neelambur, Coimbatore 641062`,
  `R M D Engineering College, Kavaraipettai, Gummidipoondi, Thiruvallur District 601206`,
  `R M K College of Engineering and Technology, Puduvoyal, Gummidipoondi Taluk, Thiruvallur District 601206`,
  `R M K Engineering College (Autonomous), Kavaraipettai, Gummidipoondi, Thiruvallur District 601206`,
  `R V S College of Engineering and Technology, Kannampalayam, Sulur, Coimbatore District 641402`,
  `R V S College of Engineering, N Paraipatti Post, Dindigul District 624005`,
  `R V S Educational Trust�s Groups of Institutions (Integrated Campus),
 N Paraipatti Post, Vedasandur Taluk, Dindigul District 624005`,
  `R V S Padmavathy College of Engineering and Technology, Senthil Pakkam Village, Roshanagaram Post, Madarapakkam Via,
 Gummidipoondi Taluk, Thiruvallur District 601202`,
  `R V S Technical Campus-Coimbatore, Kumaran Kottam Campus, Kannampalayam, Sulur, Coimbatore District 641 402`,
  `Rajaas Engineering College , Vadakkangulam, Tirunelveli District 627116`,
  `Rajalakshmi Engineering College (Autonomous), Thandalam, Sriperumpudur Taluk, Kancheepuram District 602105`,
  `Rajalakshmi Institute of Technology, Irulapalayam, Kuthampakkam Post, Kancheepuram District 602107`,
  `Rajas Institute of Technology , Ozhuginasery, Nagercoil, Kanyakumari District 629001`,
  `Rajiv Gandhi College of Engineering, Nemili, Sriperumpudur Taluk, Kancheepuram District 602105`,
  `Ramco Institute of Technology, North venganallur Village, Krishnapuram Panchayat, Rajapalayam, Virudhunagar District 626117`,
  `Ranippettai Engineering College, Thenkadappanthangal, Ranipet District 632513`,
  `Rathinam Technical Campus, Pollachi Road, Eachanari, Coimbatore District 641021`,
  `Renganayagi Varatharaj College of Engineering, Salvarpatti, Sivakasi, Virudhunagar District 626128`,
  `Roever College of Engineering and Technology, Elambalur, Perambalur District 621212`,
  `Roever Engineering College, Elambalur, Perambalur District 621212`,
  `Rohini College of Engineering & Technology, Anjugramam- Kanyakumari Main Road, Palkulam, Variyoor Post, Kanyakumari
 District 629401`,
  `Rrase College of Engineering, Padappai, Chennai 601301`,
  `S A Engineering College (Autonomous), Thiruverkadu, Chennai 600077`,
  `S K P Engineering College, Thiruvannamalai District 606611`,
  `S K R Engineering College, Poonamallee, Chennai 600123`,
  `S N S College of Engineering (Autonomous), Sathy Main Road, Kurumbapalayam Post, Coimbatore District 641107`,
  `S N S College of Technology (Autonomous), Kalappatti Post, Coimbatore District 641035`,
  `S S M College of Engineering, Komarapalayam, Namakkal District 638183`,
  `S Veerasamy Chettiar College of Engineering and Technology, Puliangudi Post, Tenkasi District 627855`,
  `SACS-M A V M M Engineering College, Kidaripatty Post, Madurai District 625001`,
  `Salem College of Engineering and Technology, Salem-Attur Main Road, NH-68, Mettupatty Perumapalayam, Salem District 636111`,
  `SAMS College of Engineering and Technology, Panappakkam, Chennai-Tirupathi Road, Uthukkottai Taluk, Thiruvallur District
 601102`,
  `Sapthagiri College of Engineering, Periyanahalli Post, Dharmapuri District 635205`,
  `Saranathan College of Engineering, Panjappur, Tiruchirappalli District 620012`,
  `Saraswathy College of Engineering and Technology, NH-45, Main Road, Olakkur, Tindivanam Taluk, Villupuram District 604307`,
  `Sardar Raja College of Engineering, Alangulam, Tenkasi District 627808`,
  `Sasurie College of Engineering, Vijayamangalam, Tiruppur District 638056`,
  `Satyam College of Engineering & Technology, Kannappannallur, Aralvaimozhi, Kanyakumari District 629301`,
  `Saveetha Engineering College (Autonomous), Thandalam, Sriperumpudur Taluk, Kancheepuram District 602105`,
  `SBM College of Engineering and Technology, Thamaraipady, T N Paraipatti Pirivu, Dindigul District 624005`,
  `SCAD College of Engineering and Technology, Cheranmahadevi, Tirunelveli District 627414`,
  `Selvam College of Technology, Pappanaickenpatti Post, Namakkal District 637003`,
  `Sembodai Rukmani Varatharajan Engineering College, Sembodai Village, Vedaraniam, Nagappattinam District 614820`,
  `Sengunthar College of Engineering, Tiruchengode, Namakkal District 637205`,
  `Sengunthar Engineering College (Autonomous), Tiruchengode, Namakkal District 637205`,
  `Sethu Institute of Technology (Autonomous), Kariapatti Post, Virudhunagar District 626106`,
  `Shanmuganathan Engineering College, Pillivalam Post, Pudukkottai District 622507`,
  `Shivani Engineering College, Ammapettai, Srirangam, Tiruchirappalli District 620009`,
  `Shree Motilal Kanhaiyalal (SMK)Fomra Institute of Technology, Old Mahabalipuram Road (OMR), Kelambakkam, Chengalpattu District
 603103`,
  `Shree Sathyam College of Engineering and Technology, NH-47, Manjakkalpatti, Kuppanur Post, Sankari Taluk, Salem District 637301`,
  `Shree Venkateshwara Hi-Tech Engineering College, Othakuthirai, K Mettupalayam Post, Gobichettipalayam, Erode District 638455`,
  `Shreenivasa Engineering College, B Pallipatti, Bommidi, Pappireddipatti Taluk, Dharmapuri District 635301`,
  `Shri Angalamman College of Engineering and Technology Siruganoor, Tiruchirappalli District 621105`,
  `Sir Issac Newton College of Engineering and Technology, Anthanapeetai Post, Papakoil, Nagappattinam District 611102`,
  `Sivaji College of Engineering and Technology, Manivilla Palulai Panchayat, Vilavancode, Kanyakumari District 629170`,
  `SMR East Coast College of Engineering & Technology, East Coast Road, Somanathapattinam, Thanjavur District 614612`,
  `SOLAIMALAI COLLEGE OF ENGINEERIG, Veerapanjan, Madurai District 625020`,
  `Sona College of Technology (Autonomous), Suramangalam Post, Salem District 636005`,
  `Sree Krishna College of Engineering, Anaicut Post, Unnai Village, Vellore District 632101`,
  `Sree Raaja Raajan College of Engineering & Technology, Amaravathi Village, Amaravathi Pudur Post, Karaikudi, Sivagangai District 630301`,
  `Sree Sakthi Engineering College, Bettathapuram, Bilichi Village, Karamadai, Coimbatore District 641104`,
  `Sree Sastha Institute of Engineering and Technology, Chembarambakkam, Chennai 600103`,
  `Sree Sowdambiga College of Engineering, Aruppukkottai Taluk, Virudhunagar District 626134`,
  `SRG Engineering College, Aniyapuram Post, Namakkal District 637017`,
  `Sri Balaji Chockalingam Engineering College, Arni, Thiruvannamalai District 632317`,
  `Sri Bharathi Engineering College for Women, Kaikkuruchi Village, Alangudi Taluk, Pudukkottai District 622303`,
  `Sri Eshwar College of Engineering (Autonomous), Kondampatti Post, Vadasithur (Via), Kinathukadavu, Coimbatore District 641202`,
  `Sri Jayaram Institute of Engineering and Technology, 51 N, Elavur, 58N, Natham, Gummidipoondi Taluk, Thiruvallur District 601201`,
  `Sri Krishna College of Engineering, Tiruttani High Road, Arakkonam, Ranipet District 631003`,
  `Sri Krishna College of Enginering and Technology (Autonomous) , Kuniamuthur, Coimbatore District 641008`,
  `Sri Krishna College of Technology (Autonomous) , Kovaipudur Post, Coimbatore District 641042`,
  `Sri Krishna Engineering College, Panappakkam, Padappai, Chennai 601301`,
  `Sri Krishna Institute of Technology, Panapakkam, Padappai, Chennai 601301`,
  `Sri Muthukumaran Institute of Technology, Near Mangadu, Chennai 600069`,
  `Sri Nandhanam College of Engineering and Technology, Thiruppathur Dt 635601`,
  `SRM Valliammai Engineering College (Autonomous), Kattankulathur, Chennai 603203`,
  `SSM Institute of Engineering and Technology, Kuttathupatti Village, Sindalaigundu Post, Dindigul District 624002`,
  `St. Annes College of Engineering and Technology, Anguchettypalayam, Siruvathur Post, Panruti, Cuddalore District
 607110`,
  `St. Joseph College of Engineering, Trinity Campus, Nemili, Sriperumpudur Taluk, Kancheepuram District 602105`,
  `St. Joseph�s College of Engineering, Old Mahabalipuram Road (OMR), Chennai 600 119`,
  `St. Josephs College of Engineering and Technology, Elupatti Village, Rawaspatti Post, Thanjavur District 613403`,
  `St. Josephs Institute of Technology, Jeppiaar Nagar, Old Mahabalipuram Road (OMR), Chennai 600119`,
  `St. Michael College of Engineering and Technology, Kalayarkoil, Sivagangai District 630551`,
  `St. Mother Theresa Engineering College, Vagaikulam, Thoothukudi District 628102`,
  `St. Peters College of Engineering and Technology, College Road, Avadi, Chennai 600 054`,
  `St. Xavier Catholic College of Engineering, Chunkankadai, Nagercoil, Kanyakumari District 629807`,
  `Star Lion College of Engineering & Technology, Manankorai Main Road, Manankorai Village, Thanjavur District 614206`,
  `Stella Marys College of Engineering, Arunthengan Vilai, Azhikal Post, Kanyakumari District 629202`,
  `Study World College of Engineering, Madukarai Post, Coimbatore - 641 105.`,
  `Sudharsan Engineering College, Sathiyamangalam Post, Pudukkottai District 622501`,
  `Suguna College of Engineering, Kalappatti Road, Civil Aerodrome Post, Coimbatore District 641014`,
  `Sureya College of Engineering, Konalai, Tiruchirappalli District 621132`,
  `Surya Engineering College, Mettukadai, Kathirampatti Post, Erode District 638107`,
  `Surya Group of Institutions, GST Road, Vikravandi Village, Villupuram District 605652`,
  `Syed Ammal Engineering College, Achuthan Vayal Post, Ramanathapuram District 623502`,
  `T J S Engineering College, Peruvoyal, Near Kavaraipettai, Gummidipoondi Taluk, Thiruvallur District 601206`,
  `T S M Jain College of Technology, Melur Village, Kallakurichi District 606201`,
  `T.J INSTITUTE OF TECHNOLOGY, KARAPAKKAM CH-97`,
  `Tagore Engineering College, Rathnamangalam, Vandalur Post, Chennai 600048`,
  `Tagore Institute of Engineering and Technology, Deviyakurichi, Attur Taluk, Salem District 636112`,
  `Tamilnadu College of Engineering, Karumathampatti Post, Coimbatore District 641659`,
  `Thamirabharani Engineering College, Chathirampudukulam Village, Thatchanallur, Tirunelveli District 625358`,
  `Thangavelu Engineering College, Karappakkam, Chennai 600097`,
  `Thanthai Periyar Government Institute of Technology, Bagayam, Vellore District 632002`,
  `The Kavery College of Engineering, M Kalipatti Post, Mecheri, Salem District 636453`,
  `The Kavery Engineering College, M Kalipatti Post, Mecheri, Salem District 634456`,
  `Theni Kammavar Sangam College of Technology, Theni Main Road, Koduvillarpatti Post, Theni District 625534`,
  `Thiagarajar College of Engineering (Autonomous),Tirupparankundram, Madurai District 625015`,
  `Thirumalai Engineering College, Kilambi, Kancheepuram District 631551`,
  `Thiruvalluvar College of Engineering and Technology, Vandavasi, Thiruvannamalai District 604505`,
  `Trichy Engineering College, Konalai, Tiruchirappalli District 621132`,
  `Udaya School of Engineering, Ammandivilai Post, Kanyakumari District 629204`,
  `Ultra College of Engineering and Technology, Kodikulam, 1 Bit Village, Madurai-Chennai Highway, Madurai District 625104`,
  `United Institute of Technology, Gadalore Village, Perianaickenpalayam, Coimbatore District 641020`,
  `Universal College of Engineering and Technology, Anbagam Campus, Radhapuram Road, Vallioor, Tirunelveli District 627117`,
  `University College of Engineering, Ariyalur, Kathankudikadu Village, Thelur Post, Ariyalur District 621704`,
  `University College of Engineering, Arni, Arni to Devikapuram Road, Thatchur, Arni, Thiruvannamalai District 632326`,
  `University College of Engineering, Dindigul, Mangarai Pirivu, Reddiyarchathiram, Dindigul District 624622`,
  `University College of Engineering, Kancheepuram, Ponnerikarai
 Campus, NH4, Chennai-Bangalore Highway, Karaipettai Village & Post, Kancheepuram District 631552`,
  `University College of Engineering, Nagercoil, Nagercoil Industrial Estate, Konam, Kanyakumari District 629004`,
  `University College of Engineering, Panruti, Chennai-Kumbakonam Highway, Panikkankuppam, Panruti, Cuddalore District 607106`,
  `University College of Engineering, Pattukkottai, ECR Road, Rajamadam, Pattukkottai Taluk, Thanjavur District 614701`,
  `University College of Engineering, Ramanathapuram, Pullangudi, Ramanathapuram District 623513`,
  `University College of Engineering, Thirukkuvalai, Nagappattinam District 610204`,
  `University College of Engineering, Tindivanam, Melpakkam, Tindivanam, Villupuram District 604001`,
  `University College of Engineering, Tiruchirappalli, (Bharathidasan Institute of Technology), Tiruchirappalli District 620024`,
  `University College of Engineering, Villupuram, Kakuppam, Villupuram District 605103`,
  `University Departments of Anna University, Chennai - ACT Campus, Sardar Patel Road, Guindy, Chennai 600 025`,
  `University Departments of Anna University, Chennai - CEG Campus, Sardar Patel Road, Guindy, Chennai 600 025`,
  `University Departments of Anna University, Chennai - MIT Campus, Chrompet, Tambaram Taluk, Chengalpattu District 600 044`,
  `University V.O.C. College of Engineering, Thoothukudi, Near V.O.C. College, Millerpuram, Thoothukudi District 628008`,
  `Unnamalai Institute of Technology, Ayyaneri, Kovilpatti, Thoothukudi District 628502`,
  `V P Muthaiah Pillai Meenakshi Ammal Engineering College for Women, Srivilliputhur Taluk, Virudhunagar District 626190`,
  `V R S College of Engineering and Technology, Arasur, Villupuram District 607107`,
  `V S A Group of Institutions, NH-47, Uthamasola Puram Post, Salem District 636010`,
  `V S B College of Engineering Technical Campus, Ealur Pirivu, Solavampalayam Post, Coimbatore District 642109`,
  `V S B Engineering College, Kovai Road, Karur District 639111`,
  `V V College of Engineering, Arasoor Village, Idaichivilai Post, Santhakulam Taluk, Thoothukudi District 628656`,
  `Vaigai College of Engineering, Therkutheru, Melur Taluk, Madurai District 625122`,
  `Vandayar Engineering College, Pulavarnatham Post, Mariamman Koil (Via), Thanjavur District 613001`,
  `Varuvan Vadivelan Institute of Technology, Nallanahalli, Dharmapuri District 636701`,
  `Veerammal Engineering College, K Singarakottai, Dindigul District 624708`,
  `Vel Tech High Tech Dr. Rangarajan Dr. Sakunthala Engineering College, Avadi-Alamathi Road, Chennai 600 062`,
  `Vel Tech Multi Tech Dr. Rangarajan Dr. Sakunthala Engineering College (Autonomous), Avadi-Alamathi Road, Chennai 600 062`,
  `Velalar College of Engineering and Technology (Autonomous), Thindal Post, Erode District 638009`,
  `Velammal College of Engineering and Technology, Madurai District 625009`,
  `Velammal Engineering College (Autonomous), Ambattur-Redhills Road, Chennai 600066`,
  `Velammal Institute of Technology, Chennai-Kolkatta Highway, Panchetti Village, Ponneri Taluk, Thiruvallur District 601204`,
  `Vetri Vinayaha College of Engineering and Technology, Namakkal- Trichy Main Road, Tholurpatti Village, Thottiam, Tiruchirappalli District 621215`,
  `Vi Institute of Technology, Sirunkundram Village & Post, Chengalpattu District 603108`,
  `Vidhya Vikkas College of Engineering and Technology, Varahoorampatti, Tiruchengode, Namakkal District 637 214`,
  `Vins Christian College of Engineering, Chunkankadai Post, Nagercoil, Kanyakumari District 629807`,
  `Vins Christian Womens College of Engineering, Chunkankadai Post, Nagercoil, Kanyakumari District 629807`,
  `Vivekanandha College of Engineering for Women (Autonomous), Sathinaickenpalayam, Elayampalayam Village, Kumaramangalam,
 Namakkal District 637205`,
  `Vivekanandha College of Technology for Women, Sathinaickenpalayam, Elayampalayam Village, Kumaramangalam,
 Namakkal District 637205`,
  `Indian Institute of Technology Bombay (IITB)`,
  `Indian Institute of Technology Delhi (IITD)`,
  `Indian Institute of Technology Madras (IITM)`,
  `Indian Institute of Technology Kanpur (IITK)`,
  `Indian Institute of Technology Kharagpur (IITKGP)`,
  `Indian Institute of Technology Roorkee (IITR)`,
  `Indian Institute of Technology Guwahati (IITG)`,
  `Indian Institute of Technology Hyderabad (IITH)`,
  `Indian Institute of Technology Gandhinagar (IITGN)`,
  `Indian Institute of Technology Patna (IITP)`,
  `Indian Institute of Technology Bhubaneswar (IITBBS)`,
  `Indian Institute of Technology Ropar (IITRPR)`,
  `Indian Institute of Technology Indore (IITI)`,
  `Indian Institute of Technology Mandi (IITMandi)`,
  `Indian Institute of Technology Jodhpur (IITJ)`,
  `Indian Institute of Technology Varanasi (IITBHU)`,
  `Indian Institute of Technology Palakkad (IITPKD)`,
  `Indian Institute of Technology Tirupati (IITTP)`,
  `Indian Institute of Technology Dhanbad (IITISM)`,
  `Indian Institute of Technology Bhilai (IITBhilai)`,
  `Indian Institute of Technology Goa (IITGoa)`,
  `Indian Institute of Technology Jammu (IITJammu)`,
  `Indian Institute of Technology Dharwad (IITDharwad)`,
  `Vellore Institute of Technology, Vellore`,
  `Vellore Institute of Technology, Chennai`,
  `Vellore Institute of Technology, Bhopal`,
  `Vellore Institute of Technology, Amaravati`,
  `SRM Institute of Science and Technology, Kattankulathur`,
  `SRM Institute of Science and Technology, Ramapuram`,
  `SRM Institute of Science and Technology, Vadapalani`,
  `SRM Institute of Science and Technology, NCR Campus`,
  `SRM University, Sonepat`,
  `SRM University, Andhra Pradesh`,
  `Amity University Noida (Main Campus)`,
  `Amity University Lucknow`,
  `Amity University Jaipur`,
  `Amity University Gurgaon`,
  `Amity University Gwalior`,
  `Amity University Mumbai`,
  `Amity University Raipur`,
  `Amity University Kolkata`,
  `Amity University Ranchi`,
  `Amity University Patna`,
  `Amity University Kochi`,
  `Amity University Ahmedabad`,
  `Amity University Chennai`,
  `Amity University Bengaluru`,
  `Amity University Greater Noida (Noida Campus 2)`,
  `Amity University Gurugram`,
  `Amity University Bhubaneswar`,
  `Amity University Pune`,
  `Amity University Kolkata (Amity Global Business School)`,
  `Amity University Mumbai (Amity Global Business School)`,
  `Amity University Bengaluru (Amity Global Business School)`,
  `Amity University Hyderabad (Amity Global Business School)`,
  `Amity University Noida (Amity Global Business School)`,
  `Amity University Chennai (Amity Global Business School)`,
  `Amity University Ahmedabad (Amity Global Business School)`,
  `Amity University Kolkata (Amity School of Engineering)`,
  `Amity University Noida (Amity School of Engineering)`,
  `Amity University Jaipur (Amity School of Engineering)`,
  `Amity University Lucknow (Amity School of Engineering)`,
  `Amity University Mumbai (Amity School of Engineering)`,
  `Amity University Raipur (Amity School of Engineering)`,
  `Amity University Greater Noida (Amity School of Engineering)`,
  `Manipal Academy of Higher Education, Manipal`,
  `Manipal Academy of Higher Education, Jaipur`,
  `Manipal Academy of Higher Education, Sikkim`,
  `Manipal Academy of Higher Education, Mangalore`,
  `Manipal Academy of Higher Education, Bangalore`,
  `Manipal Academy of Higher Education, Jaipur-Ajmer`,
  `Manipal Academy of Higher Education, Bengaluru`,
  `Manipal Academy of Higher Education, Vijayawada`,
  `Manipal Academy of Higher Education, Mumbai`,
  `Manipal Academy of Higher Education, Noida`,
  `Manipal Academy of Higher Education, Chandigarh`,
  `Manipal Academy of Higher Education, Indore`,
  `Manipal Academy of Higher Education, Greater Noida`,
  `Manipal Academy of Higher Education, Patna`,
  `Manipal Academy of Higher Education, Dehradun`,
  `Manipal Academy of Higher Education, Jaipur-Rajasthan`,
  `University of Delhi`,
  `Jawaharlal Nehru University`,
  `University of Hyderabad`,
  `University of Calcutta`,
  `Banaras Hindu University`,
  `University of Mumbai`,
  `Jadavpur University`,
  `Anna University`,
  `University of Madras`,
  `Savitribai Phule Pune University`,
  `University of Calicut`,
  `Panjab University`,
  `Osmania University`,
  `University of Allahabad`,
  `University of Mysore`,
  `Amrita Vishwa Vidyapeetham, Amritapuri Campus`,
  `Amrita Vishwa Vidyapeetham, Bengaluru Campus`,
  `Amrita Vishwa Vidyapeetham, Coimbatore Campus`,
  `Amrita Vishwa Vidyapeetham, Kochi Campus`,
  `Amrita Vishwa Vidyapeetham, Mysuru Campus`,
  `Amrita Vishwa Vidyapeetham, Chennai Campus`,
  `Amrita Vishwa Vidyapeetham, Amaravati Campus`,
  `Sathyabama Institute of Science and Technology, Chennai Campus`,
  `National Institute of Technology Andhra Pradesh (NITAP)`,
  `National Institute of Technology Arunachal Pradesh (NITAP)`,
  `National Institute of Technology Agartala (NITA)`,
  `Motilal Nehru National Institute of Technology Allahabad (MNNIT)`,
  `Maulana Azad National Institute of Technology Bhopal (MANIT)`,
  `National Institute of Technology Calicut (NITC)`,
  `National Institute of Technology Delhi (NITD)`,
  `National Institute of Technology Durgapur (NITD)`,
  `National Institute of Technology Goa (NITG)`,
  `National Institute of Technology Hamirpur (NITH)`,
  `Malaviya National Institute of Technology Jaipur (MNIT)`,
  `Dr. B. R. Ambedkar National Institute of Technology Jalandhar (NITJ)`,
  `National Institute of Technology Jamshedpur (NITJSR)`,
  `National Institute of Technology Kurukshetra (NITKKR)`,
  `National Institute of Technology Manipur (NITMN)`,
  `National Institute of Technology Meghalaya (NITM)`,
  `National Institute of Technology Mizoram (NITMZ)`,
  `National Institute of Technology Nagaland (NITN)`,
  `Visvesvaraya National Institute of Technology Nagpur (VNIT)`,
  `National Institute of Technology Patna (NITP)`,
  `National Institute of Technology Puducherry (NITPY)`,
  `National Institute of Technology Raipur (NITRR)`,
  `National Institute of Technology Rourkela (NITR)`,
  `National Institute of Technology Sikkim (NITSKM)`,
  `National Institute of Technology Silchar (NITS)`,
  `National Institute of Technology Srinagar (NITSRI)`,
  `Sardar Vallabhbhai National Institute of Technology Surat (SVNIT)`,
  `National Institute of Technology Surathkal (NITK)`,
  `National Institute of Technology Tiruchirappalli (NITT)`,
  `National Institute of Technology Uttarakhand (NITUK)`,
  `National Institute of Technology Warangal (NITW)`,
  `Birla Institute of Technology, Mesra (BIT Mesra)`,
  `Birla Institute of Technology and Science, Pilani (BITS Pilani)`,
  `Birla Institute of Technology, Patna (BIT Patna)`,
  `Birla Institute of Technology, Deogarh (BIT Deogarh)`,
  `Birla Institute of Technology, Jaipur (BIT Jaipur)`,
  `Birla Institute of Technology, Lalpur (BIT Lalpur)`,
  `Birla Institute of Technology, Noida (BIT Noida)`,
  `Birla Institute of Technology, Allahabad (BIT Allahabad)`,
  `Birla Institute of Technology, Kolkata (BIT Kolkata)`,
  `Birla Institute of Technology, Ranchi (BIT Ranchi)`,
  `Birla Institute of Technology, South Extension (BIT,SE)`,
  `PSGR Krishnammal College for Women, Coimbatore`,
];

colleges.sort();

export default colleges;
